// Code generated by entc, DO NOT EDIT.

package pregnant

const (
	// Label holds the string label denoting the pregnant type in the database.
	Label = "pregnant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPREGNANTNAME holds the string denoting the pregnant_name field in the database.
	FieldPREGNANTNAME = "pregnant_name"
	// FieldPREGNANTAGE holds the string denoting the pregnant_age field in the database.
	FieldPREGNANTAGE = "pregnant_age"

	// EdgeSETMOM holds the string denoting the setmom edge name in mutations.
	EdgeSETMOM = "SETMOM"

	// Table holds the table name of the pregnant in the database.
	Table = "pregnants"
	// SETMOMTable is the table the holds the SETMOM relation/edge.
	SETMOMTable = "antenatals"
	// SETMOMInverseTable is the table name for the Antenatal entity.
	// It exists in this package in order to avoid circular dependency with the "antenatal" package.
	SETMOMInverseTable = "antenatals"
	// SETMOMColumn is the table column denoting the SETMOM relation/edge.
	SETMOMColumn = "pregnant_setmom"
)

// Columns holds all SQL columns for pregnant fields.
var Columns = []string{
	FieldID,
	FieldPREGNANTNAME,
	FieldPREGNANTAGE,
}

var (
	// PREGNANTNAMEValidator is a validator for the "PREGNANT_NAME" field. It is called by the builders before save.
	PREGNANTNAMEValidator func(string) error
	// PREGNANTAGEValidator is a validator for the "PREGNANT_AGE" field. It is called by the builders before save.
	PREGNANTAGEValidator func(int) error
)
