// Code generated by entc, DO NOT EDIT.

package pregnant

import (
	"github.com/F12aPPy/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PREGNANTNAME applies equality check predicate on the "PREGNANT_NAME" field. It's identical to PREGNANTNAMEEQ.
func PREGNANTNAME(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTAGE applies equality check predicate on the "PREGNANT_AGE" field. It's identical to PREGNANTAGEEQ.
func PREGNANTAGE(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPREGNANTAGE), v))
	})
}

// PREGNANTNAMEEQ applies the EQ predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEEQ(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMENEQ applies the NEQ predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMENEQ(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEIn applies the In predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEIn(vs ...string) predicate.Pregnant {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Pregnant(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPREGNANTNAME), v...))
	})
}

// PREGNANTNAMENotIn applies the NotIn predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMENotIn(vs ...string) predicate.Pregnant {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Pregnant(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPREGNANTNAME), v...))
	})
}

// PREGNANTNAMEGT applies the GT predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEGT(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEGTE applies the GTE predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEGTE(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMELT applies the LT predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMELT(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMELTE applies the LTE predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMELTE(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEContains applies the Contains predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEContains(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEHasPrefix applies the HasPrefix predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEHasPrefix(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEHasSuffix applies the HasSuffix predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEHasSuffix(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEEqualFold applies the EqualFold predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEEqualFold(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTNAMEContainsFold applies the ContainsFold predicate on the "PREGNANT_NAME" field.
func PREGNANTNAMEContainsFold(v string) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPREGNANTNAME), v))
	})
}

// PREGNANTAGEEQ applies the EQ predicate on the "PREGNANT_AGE" field.
func PREGNANTAGEEQ(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPREGNANTAGE), v))
	})
}

// PREGNANTAGENEQ applies the NEQ predicate on the "PREGNANT_AGE" field.
func PREGNANTAGENEQ(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPREGNANTAGE), v))
	})
}

// PREGNANTAGEIn applies the In predicate on the "PREGNANT_AGE" field.
func PREGNANTAGEIn(vs ...int) predicate.Pregnant {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Pregnant(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPREGNANTAGE), v...))
	})
}

// PREGNANTAGENotIn applies the NotIn predicate on the "PREGNANT_AGE" field.
func PREGNANTAGENotIn(vs ...int) predicate.Pregnant {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Pregnant(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPREGNANTAGE), v...))
	})
}

// PREGNANTAGEGT applies the GT predicate on the "PREGNANT_AGE" field.
func PREGNANTAGEGT(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPREGNANTAGE), v))
	})
}

// PREGNANTAGEGTE applies the GTE predicate on the "PREGNANT_AGE" field.
func PREGNANTAGEGTE(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPREGNANTAGE), v))
	})
}

// PREGNANTAGELT applies the LT predicate on the "PREGNANT_AGE" field.
func PREGNANTAGELT(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPREGNANTAGE), v))
	})
}

// PREGNANTAGELTE applies the LTE predicate on the "PREGNANT_AGE" field.
func PREGNANTAGELTE(v int) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPREGNANTAGE), v))
	})
}

// HasSETMOM applies the HasEdge predicate on the "SETMOM" edge.
func HasSETMOM() predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SETMOMTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SETMOMTable, SETMOMColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSETMOMWith applies the HasEdge predicate on the "SETMOM" edge with a given conditions (other predicates).
func HasSETMOMWith(preds ...predicate.Antenatal) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SETMOMInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SETMOMTable, SETMOMColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Pregnant) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Pregnant) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Pregnant) predicate.Pregnant {
	return predicate.Pregnant(func(s *sql.Selector) {
		p(s.Not())
	})
}
