// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Antenatal is the predicate function for antenatal builders.
type Antenatal func(*sql.Selector)

// Babystatus is the predicate function for babystatus builders.
type Babystatus func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
