// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"
	// FieldPatientAge holds the string denoting the patient_age field in the database.
	FieldPatientAge = "patient_age"

	// EdgeSETMOM holds the string denoting the setmom edge name in mutations.
	EdgeSETMOM = "SETMOM"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// SETMOMTable is the table the holds the SETMOM relation/edge.
	SETMOMTable = "antenatals"
	// SETMOMInverseTable is the table name for the Antenatal entity.
	// It exists in this package in order to avoid circular dependency with the "antenatal" package.
	SETMOMInverseTable = "antenatals"
	// SETMOMColumn is the table column denoting the SETMOM relation/edge.
	SETMOMColumn = "patient_setmom"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
	FieldPatientAge,
}

var (
	// PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
	// PatientAgeValidator is a validator for the "patient_age" field. It is called by the builders before save.
	PatientAgeValidator func(int) error
)
