// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/F12aPPy/app/ent/antenatal"
	"github.com/F12aPPy/app/ent/babystatus"
	"github.com/F12aPPy/app/ent/patient"
	"github.com/F12aPPy/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// AntenatalCreate is the builder for creating a Antenatal entity.
type AntenatalCreate struct {
	config
	mutation *AntenatalMutation
	hooks    []Hook
}

// SetADDEDTIME sets the ADDED_TIME field.
func (ac *AntenatalCreate) SetADDEDTIME(t time.Time) *AntenatalCreate {
	ac.mutation.SetADDEDTIME(t)
	return ac
}

// SetNillableADDEDTIME sets the ADDED_TIME field if the given value is not nil.
func (ac *AntenatalCreate) SetNillableADDEDTIME(t *time.Time) *AntenatalCreate {
	if t != nil {
		ac.SetADDEDTIME(*t)
	}
	return ac
}

// SetGETMOMID sets the GETMOM edge to Patient by id.
func (ac *AntenatalCreate) SetGETMOMID(id int) *AntenatalCreate {
	ac.mutation.SetGETMOMID(id)
	return ac
}

// SetNillableGETMOMID sets the GETMOM edge to Patient by id if the given value is not nil.
func (ac *AntenatalCreate) SetNillableGETMOMID(id *int) *AntenatalCreate {
	if id != nil {
		ac = ac.SetGETMOMID(*id)
	}
	return ac
}

// SetGETMOM sets the GETMOM edge to Patient.
func (ac *AntenatalCreate) SetGETMOM(p *Patient) *AntenatalCreate {
	return ac.SetGETMOMID(p.ID)
}

// SetTAKECAREID sets the TAKECARE edge to User by id.
func (ac *AntenatalCreate) SetTAKECAREID(id int) *AntenatalCreate {
	ac.mutation.SetTAKECAREID(id)
	return ac
}

// SetNillableTAKECAREID sets the TAKECARE edge to User by id if the given value is not nil.
func (ac *AntenatalCreate) SetNillableTAKECAREID(id *int) *AntenatalCreate {
	if id != nil {
		ac = ac.SetTAKECAREID(*id)
	}
	return ac
}

// SetTAKECARE sets the TAKECARE edge to User.
func (ac *AntenatalCreate) SetTAKECARE(u *User) *AntenatalCreate {
	return ac.SetTAKECAREID(u.ID)
}

// SetGETSTATUSID sets the GETSTATUS edge to Babystatus by id.
func (ac *AntenatalCreate) SetGETSTATUSID(id int) *AntenatalCreate {
	ac.mutation.SetGETSTATUSID(id)
	return ac
}

// SetNillableGETSTATUSID sets the GETSTATUS edge to Babystatus by id if the given value is not nil.
func (ac *AntenatalCreate) SetNillableGETSTATUSID(id *int) *AntenatalCreate {
	if id != nil {
		ac = ac.SetGETSTATUSID(*id)
	}
	return ac
}

// SetGETSTATUS sets the GETSTATUS edge to Babystatus.
func (ac *AntenatalCreate) SetGETSTATUS(b *Babystatus) *AntenatalCreate {
	return ac.SetGETSTATUSID(b.ID)
}

// Mutation returns the AntenatalMutation object of the builder.
func (ac *AntenatalCreate) Mutation() *AntenatalMutation {
	return ac.mutation
}

// Save creates the Antenatal in the database.
func (ac *AntenatalCreate) Save(ctx context.Context) (*Antenatal, error) {
	if _, ok := ac.mutation.ADDEDTIME(); !ok {
		v := antenatal.DefaultADDEDTIME()
		ac.mutation.SetADDEDTIME(v)
	}
	var (
		err  error
		node *Antenatal
	)
	if len(ac.hooks) == 0 {
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AntenatalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AntenatalCreate) SaveX(ctx context.Context) *Antenatal {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ac *AntenatalCreate) sqlSave(ctx context.Context) (*Antenatal, error) {
	a, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	a.ID = int(id)
	return a, nil
}

func (ac *AntenatalCreate) createSpec() (*Antenatal, *sqlgraph.CreateSpec) {
	var (
		a     = &Antenatal{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: antenatal.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: antenatal.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.ADDEDTIME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: antenatal.FieldADDEDTIME,
		})
		a.ADDEDTIME = value
	}
	if nodes := ac.mutation.GETMOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   antenatal.GETMOMTable,
			Columns: []string{antenatal.GETMOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: patient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TAKECAREIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   antenatal.TAKECARETable,
			Columns: []string{antenatal.TAKECAREColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.GETSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   antenatal.GETSTATUSTable,
			Columns: []string{antenatal.GETSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: babystatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return a, _spec
}
