// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/F12aPPy/app/ent/antenatal"
	"github.com/F12aPPy/app/ent/babystatus"
	"github.com/F12aPPy/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BabystatusUpdate is the builder for updating Babystatus entities.
type BabystatusUpdate struct {
	config
	hooks      []Hook
	mutation   *BabystatusMutation
	predicates []predicate.Babystatus
}

// Where adds a new predicate for the builder.
func (bu *BabystatusUpdate) Where(ps ...predicate.Babystatus) *BabystatusUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetSTATUSBABYNAME sets the STATUS_BABY_NAME field.
func (bu *BabystatusUpdate) SetSTATUSBABYNAME(s string) *BabystatusUpdate {
	bu.mutation.SetSTATUSBABYNAME(s)
	return bu
}

// AddSETSTATUSIDs adds the SETSTATUS edge to Antenatal by ids.
func (bu *BabystatusUpdate) AddSETSTATUSIDs(ids ...int) *BabystatusUpdate {
	bu.mutation.AddSETSTATUSIDs(ids...)
	return bu
}

// AddSETSTATUS adds the SETSTATUS edges to Antenatal.
func (bu *BabystatusUpdate) AddSETSTATUS(a ...*Antenatal) *BabystatusUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return bu.AddSETSTATUSIDs(ids...)
}

// Mutation returns the BabystatusMutation object of the builder.
func (bu *BabystatusUpdate) Mutation() *BabystatusMutation {
	return bu.mutation
}

// RemoveSETSTATUSIDs removes the SETSTATUS edge to Antenatal by ids.
func (bu *BabystatusUpdate) RemoveSETSTATUSIDs(ids ...int) *BabystatusUpdate {
	bu.mutation.RemoveSETSTATUSIDs(ids...)
	return bu
}

// RemoveSETSTATUS removes SETSTATUS edges to Antenatal.
func (bu *BabystatusUpdate) RemoveSETSTATUS(a ...*Antenatal) *BabystatusUpdate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return bu.RemoveSETSTATUSIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BabystatusUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := bu.mutation.STATUSBABYNAME(); ok {
		if err := babystatus.STATUSBABYNAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "STATUS_BABY_NAME", err: fmt.Errorf("ent: validator failed for field \"STATUS_BABY_NAME\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BabystatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BabystatusUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BabystatusUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BabystatusUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BabystatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   babystatus.Table,
			Columns: babystatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: babystatus.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.STATUSBABYNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: babystatus.FieldSTATUSBABYNAME,
		})
	}
	if nodes := bu.mutation.RemovedSETSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   babystatus.SETSTATUSTable,
			Columns: []string{babystatus.SETSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: antenatal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.SETSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   babystatus.SETSTATUSTable,
			Columns: []string{babystatus.SETSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: antenatal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{babystatus.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BabystatusUpdateOne is the builder for updating a single Babystatus entity.
type BabystatusUpdateOne struct {
	config
	hooks    []Hook
	mutation *BabystatusMutation
}

// SetSTATUSBABYNAME sets the STATUS_BABY_NAME field.
func (buo *BabystatusUpdateOne) SetSTATUSBABYNAME(s string) *BabystatusUpdateOne {
	buo.mutation.SetSTATUSBABYNAME(s)
	return buo
}

// AddSETSTATUSIDs adds the SETSTATUS edge to Antenatal by ids.
func (buo *BabystatusUpdateOne) AddSETSTATUSIDs(ids ...int) *BabystatusUpdateOne {
	buo.mutation.AddSETSTATUSIDs(ids...)
	return buo
}

// AddSETSTATUS adds the SETSTATUS edges to Antenatal.
func (buo *BabystatusUpdateOne) AddSETSTATUS(a ...*Antenatal) *BabystatusUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return buo.AddSETSTATUSIDs(ids...)
}

// Mutation returns the BabystatusMutation object of the builder.
func (buo *BabystatusUpdateOne) Mutation() *BabystatusMutation {
	return buo.mutation
}

// RemoveSETSTATUSIDs removes the SETSTATUS edge to Antenatal by ids.
func (buo *BabystatusUpdateOne) RemoveSETSTATUSIDs(ids ...int) *BabystatusUpdateOne {
	buo.mutation.RemoveSETSTATUSIDs(ids...)
	return buo
}

// RemoveSETSTATUS removes SETSTATUS edges to Antenatal.
func (buo *BabystatusUpdateOne) RemoveSETSTATUS(a ...*Antenatal) *BabystatusUpdateOne {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return buo.RemoveSETSTATUSIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (buo *BabystatusUpdateOne) Save(ctx context.Context) (*Babystatus, error) {
	if v, ok := buo.mutation.STATUSBABYNAME(); ok {
		if err := babystatus.STATUSBABYNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "STATUS_BABY_NAME", err: fmt.Errorf("ent: validator failed for field \"STATUS_BABY_NAME\": %w", err)}
		}
	}

	var (
		err  error
		node *Babystatus
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BabystatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BabystatusUpdateOne) SaveX(ctx context.Context) *Babystatus {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BabystatusUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BabystatusUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BabystatusUpdateOne) sqlSave(ctx context.Context) (b *Babystatus, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   babystatus.Table,
			Columns: babystatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: babystatus.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Babystatus.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := buo.mutation.STATUSBABYNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: babystatus.FieldSTATUSBABYNAME,
		})
	}
	if nodes := buo.mutation.RemovedSETSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   babystatus.SETSTATUSTable,
			Columns: []string{babystatus.SETSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: antenatal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.SETSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   babystatus.SETSTATUSTable,
			Columns: []string{babystatus.SETSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: antenatal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	b = &Babystatus{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{babystatus.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
