// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/F12aPPy/app/ent/antenatal"
	"github.com/F12aPPy/app/ent/pregnant"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// PregnantCreate is the builder for creating a Pregnant entity.
type PregnantCreate struct {
	config
	mutation *PregnantMutation
	hooks    []Hook
}

// SetPREGNANTNAME sets the PREGNANT_NAME field.
func (pc *PregnantCreate) SetPREGNANTNAME(s string) *PregnantCreate {
	pc.mutation.SetPREGNANTNAME(s)
	return pc
}

// SetPREGNANTAGE sets the PREGNANT_AGE field.
func (pc *PregnantCreate) SetPREGNANTAGE(i int) *PregnantCreate {
	pc.mutation.SetPREGNANTAGE(i)
	return pc
}

// AddSETMOMIDs adds the SETMOM edge to Antenatal by ids.
func (pc *PregnantCreate) AddSETMOMIDs(ids ...int) *PregnantCreate {
	pc.mutation.AddSETMOMIDs(ids...)
	return pc
}

// AddSETMOM adds the SETMOM edges to Antenatal.
func (pc *PregnantCreate) AddSETMOM(a ...*Antenatal) *PregnantCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return pc.AddSETMOMIDs(ids...)
}

// Mutation returns the PregnantMutation object of the builder.
func (pc *PregnantCreate) Mutation() *PregnantMutation {
	return pc.mutation
}

// Save creates the Pregnant in the database.
func (pc *PregnantCreate) Save(ctx context.Context) (*Pregnant, error) {
	if _, ok := pc.mutation.PREGNANTNAME(); !ok {
		return nil, &ValidationError{Name: "PREGNANT_NAME", err: errors.New("ent: missing required field \"PREGNANT_NAME\"")}
	}
	if v, ok := pc.mutation.PREGNANTNAME(); ok {
		if err := pregnant.PREGNANTNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "PREGNANT_NAME", err: fmt.Errorf("ent: validator failed for field \"PREGNANT_NAME\": %w", err)}
		}
	}
	if _, ok := pc.mutation.PREGNANTAGE(); !ok {
		return nil, &ValidationError{Name: "PREGNANT_AGE", err: errors.New("ent: missing required field \"PREGNANT_AGE\"")}
	}
	if v, ok := pc.mutation.PREGNANTAGE(); ok {
		if err := pregnant.PREGNANTAGEValidator(v); err != nil {
			return nil, &ValidationError{Name: "PREGNANT_AGE", err: fmt.Errorf("ent: validator failed for field \"PREGNANT_AGE\": %w", err)}
		}
	}
	var (
		err  error
		node *Pregnant
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PregnantMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PregnantCreate) SaveX(ctx context.Context) *Pregnant {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PregnantCreate) sqlSave(ctx context.Context) (*Pregnant, error) {
	pr, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pr.ID = int(id)
	return pr, nil
}

func (pc *PregnantCreate) createSpec() (*Pregnant, *sqlgraph.CreateSpec) {
	var (
		pr    = &Pregnant{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pregnant.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pregnant.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.PREGNANTNAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pregnant.FieldPREGNANTNAME,
		})
		pr.PREGNANTNAME = value
	}
	if value, ok := pc.mutation.PREGNANTAGE(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: pregnant.FieldPREGNANTAGE,
		})
		pr.PREGNANTAGE = value
	}
	if nodes := pc.mutation.SETMOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pregnant.SETMOMTable,
			Columns: []string{pregnant.SETMOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: antenatal.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pr, _spec
}
