// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/F12aPPy/app/ent/pregnant"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Pregnant is the model entity for the Pregnant schema.
type Pregnant struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PREGNANTNAME holds the value of the "PREGNANT_NAME" field.
	PREGNANTNAME string `json:"PREGNANT_NAME,omitempty"`
	// PREGNANTAGE holds the value of the "PREGNANT_AGE" field.
	PREGNANTAGE int `json:"PREGNANT_AGE,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PregnantQuery when eager-loading is set.
	Edges PregnantEdges `json:"edges"`
}

// PregnantEdges holds the relations/edges for other nodes in the graph.
type PregnantEdges struct {
	// SETMOM holds the value of the SETMOM edge.
	SETMOM []*Antenatal
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SETMOMOrErr returns the SETMOM value or an error if the edge
// was not loaded in eager-loading.
func (e PregnantEdges) SETMOMOrErr() ([]*Antenatal, error) {
	if e.loadedTypes[0] {
		return e.SETMOM, nil
	}
	return nil, &NotLoadedError{edge: "SETMOM"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pregnant) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // PREGNANT_NAME
		&sql.NullInt64{},  // PREGNANT_AGE
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pregnant fields.
func (pr *Pregnant) assignValues(values ...interface{}) error {
	if m, n := len(values), len(pregnant.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	pr.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field PREGNANT_NAME", values[0])
	} else if value.Valid {
		pr.PREGNANTNAME = value.String
	}
	if value, ok := values[1].(*sql.NullInt64); !ok {
		return fmt.Errorf("unexpected type %T for field PREGNANT_AGE", values[1])
	} else if value.Valid {
		pr.PREGNANTAGE = int(value.Int64)
	}
	return nil
}

// QuerySETMOM queries the SETMOM edge of the Pregnant.
func (pr *Pregnant) QuerySETMOM() *AntenatalQuery {
	return (&PregnantClient{config: pr.config}).QuerySETMOM(pr)
}

// Update returns a builder for updating this Pregnant.
// Note that, you need to call Pregnant.Unwrap() before calling this method, if this Pregnant
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Pregnant) Update() *PregnantUpdateOne {
	return (&PregnantClient{config: pr.config}).UpdateOne(pr)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (pr *Pregnant) Unwrap() *Pregnant {
	tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pregnant is not a transactional entity")
	}
	pr.config.driver = tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Pregnant) String() string {
	var builder strings.Builder
	builder.WriteString("Pregnant(")
	builder.WriteString(fmt.Sprintf("id=%v", pr.ID))
	builder.WriteString(", PREGNANT_NAME=")
	builder.WriteString(pr.PREGNANTNAME)
	builder.WriteString(", PREGNANT_AGE=")
	builder.WriteString(fmt.Sprintf("%v", pr.PREGNANTAGE))
	builder.WriteByte(')')
	return builder.String()
}

// Pregnants is a parsable slice of Pregnant.
type Pregnants []*Pregnant

func (pr Pregnants) config(cfg config) {
	for _i := range pr {
		pr[_i].config = cfg
	}
}
