// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/F12aPPy/app/ent/antenatal"
	"github.com/F12aPPy/app/ent/babystatus"
	"github.com/F12aPPy/app/ent/patient"
	"github.com/F12aPPy/app/ent/schema"
	"github.com/F12aPPy/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	antenatalFields := schema.Antenatal{}.Fields()
	_ = antenatalFields
	// antenatalDescADDEDTIME is the schema descriptor for ADDED_TIME field.
	antenatalDescADDEDTIME := antenatalFields[0].Descriptor()
	// antenatal.DefaultADDEDTIME holds the default value on creation for the ADDED_TIME field.
	antenatal.DefaultADDEDTIME = antenatalDescADDEDTIME.Default.(func() time.Time)
	babystatusFields := schema.Babystatus{}.Fields()
	_ = babystatusFields
	// babystatusDescSTATUSBABYNAME is the schema descriptor for STATUS_BABY_NAME field.
	babystatusDescSTATUSBABYNAME := babystatusFields[0].Descriptor()
	// babystatus.STATUSBABYNAMEValidator is a validator for the "STATUS_BABY_NAME" field. It is called by the builders before save.
	babystatus.STATUSBABYNAMEValidator = babystatusDescSTATUSBABYNAME.Validators[0].(func(string) error)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescPatientName is the schema descriptor for patient_name field.
	patientDescPatientName := patientFields[0].Descriptor()
	// patient.PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	patient.PatientNameValidator = patientDescPatientName.Validators[0].(func(string) error)
	// patientDescPatientAge is the schema descriptor for patient_age field.
	patientDescPatientAge := patientFields[1].Descriptor()
	// patient.PatientAgeValidator is a validator for the "patient_age" field. It is called by the builders before save.
	patient.PatientAgeValidator = patientDescPatientAge.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUSEREMAIL is the schema descriptor for USER_EMAIL field.
	userDescUSEREMAIL := userFields[0].Descriptor()
	// user.USEREMAILValidator is a validator for the "USER_EMAIL" field. It is called by the builders before save.
	user.USEREMAILValidator = userDescUSEREMAIL.Validators[0].(func(string) error)
	// userDescUSERNAME is the schema descriptor for USER_NAME field.
	userDescUSERNAME := userFields[1].Descriptor()
	// user.USERNAMEValidator is a validator for the "USER_NAME" field. It is called by the builders before save.
	user.USERNAMEValidator = userDescUSERNAME.Validators[0].(func(string) error)
}
