// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// AntenatalsColumns holds the columns for the "antenatals" table.
	AntenatalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "added_time", Type: field.TypeTime},
		{Name: "babystatus_setstatus", Type: field.TypeInt, Nullable: true},
		{Name: "pregnant_setmom", Type: field.TypeInt, Nullable: true},
		{Name: "user_care", Type: field.TypeInt, Nullable: true},
	}
	// AntenatalsTable holds the schema information for the "antenatals" table.
	AntenatalsTable = &schema.Table{
		Name:       "antenatals",
		Columns:    AntenatalsColumns,
		PrimaryKey: []*schema.Column{AntenatalsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "antenatals_babystatuses_SETSTATUS",
				Columns: []*schema.Column{AntenatalsColumns[2]},

				RefColumns: []*schema.Column{BabystatusesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "antenatals_pregnants_SETMOM",
				Columns: []*schema.Column{AntenatalsColumns[3]},

				RefColumns: []*schema.Column{PregnantsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "antenatals_users_CARE",
				Columns: []*schema.Column{AntenatalsColumns[4]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// BabystatusesColumns holds the columns for the "babystatuses" table.
	BabystatusesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status_baby_name", Type: field.TypeString},
	}
	// BabystatusesTable holds the schema information for the "babystatuses" table.
	BabystatusesTable = &schema.Table{
		Name:        "babystatuses",
		Columns:     BabystatusesColumns,
		PrimaryKey:  []*schema.Column{BabystatusesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PregnantsColumns holds the columns for the "pregnants" table.
	PregnantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "pregnant_name", Type: field.TypeString},
		{Name: "pregnant_age", Type: field.TypeInt},
	}
	// PregnantsTable holds the schema information for the "pregnants" table.
	PregnantsTable = &schema.Table{
		Name:        "pregnants",
		Columns:     PregnantsColumns,
		PrimaryKey:  []*schema.Column{PregnantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_email", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AntenatalsTable,
		BabystatusesTable,
		PregnantsTable,
		UsersTable,
	}
)

func init() {
	AntenatalsTable.ForeignKeys[0].RefTable = BabystatusesTable
	AntenatalsTable.ForeignKeys[1].RefTable = PregnantsTable
	AntenatalsTable.ForeignKeys[2].RefTable = UsersTable
}
