// Code generated by entc, DO NOT EDIT.

package status

const (
	// Label holds the string label denoting the status type in the database.
	Label = "status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSTATUSBABYNAME holds the string denoting the status_baby_name field in the database.
	FieldSTATUSBABYNAME = "status_baby_name"

	// EdgeSETSTATUS holds the string denoting the setstatus edge name in mutations.
	EdgeSETSTATUS = "SETSTATUS"

	// Table holds the table name of the status in the database.
	Table = "status"
	// SETSTATUSTable is the table the holds the SETSTATUS relation/edge.
	SETSTATUSTable = "antenatals"
	// SETSTATUSInverseTable is the table name for the Antenatal entity.
	// It exists in this package in order to avoid circular dependency with the "antenatal" package.
	SETSTATUSInverseTable = "antenatals"
	// SETSTATUSColumn is the table column denoting the SETSTATUS relation/edge.
	SETSTATUSColumn = "status_setstatus"
)

// Columns holds all SQL columns for status fields.
var Columns = []string{
	FieldID,
	FieldSTATUSBABYNAME,
}

var (
	// STATUSBABYNAMEValidator is a validator for the "STATUS_BABY_NAME" field. It is called by the builders before save.
	STATUSBABYNAMEValidator func(string) error
)
