// Code generated by entc, DO NOT EDIT.

package status

import (
	"github.com/F12aPPy/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// STATUSBABYNAME applies equality check predicate on the "STATUS_BABY_NAME" field. It's identical to STATUSBABYNAMEEQ.
func STATUSBABYNAME(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEEQ applies the EQ predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEEQ(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMENEQ applies the NEQ predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMENEQ(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEIn applies the In predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEIn(vs ...string) predicate.Status {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Status(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSTATUSBABYNAME), v...))
	})
}

// STATUSBABYNAMENotIn applies the NotIn predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMENotIn(vs ...string) predicate.Status {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Status(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSTATUSBABYNAME), v...))
	})
}

// STATUSBABYNAMEGT applies the GT predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEGT(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEGTE applies the GTE predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEGTE(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMELT applies the LT predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMELT(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMELTE applies the LTE predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMELTE(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEContains applies the Contains predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEContains(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEHasPrefix applies the HasPrefix predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEHasPrefix(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEHasSuffix applies the HasSuffix predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEHasSuffix(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEEqualFold applies the EqualFold predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEEqualFold(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSTATUSBABYNAME), v))
	})
}

// STATUSBABYNAMEContainsFold applies the ContainsFold predicate on the "STATUS_BABY_NAME" field.
func STATUSBABYNAMEContainsFold(v string) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSTATUSBABYNAME), v))
	})
}

// HasSETSTATUS applies the HasEdge predicate on the "SETSTATUS" edge.
func HasSETSTATUS() predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SETSTATUSTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SETSTATUSTable, SETSTATUSColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSETSTATUSWith applies the HasEdge predicate on the "SETSTATUS" edge with a given conditions (other predicates).
func HasSETSTATUSWith(preds ...predicate.Antenatal) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SETSTATUSInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SETSTATUSTable, SETSTATUSColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Status) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Status) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Status) predicate.Status {
	return predicate.Status(func(s *sql.Selector) {
		p(s.Not())
	})
}
